name: chromium
services:
  chromium:
    image: rshmyrev/chromium
    build: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro # X11
      - $XDG_RUNTIME_DIR/pulse:$XDG_RUNTIME_DIR/pulse:ro # PulseAudio
      - home:/home/user
      - $HOME/Downloads:/home/user/Downloads
    environment:
      DISPLAY: ${DISPLAY} # X11
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native # PulseAudio
    cap_drop:
      - ALL
    devices:
      - /dev/dri
    hostname: debian
    security_opt:
      - no-new-privileges:true
    shm_size: 1GB

volumes:
  home:
    name: chromium_home
